org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07

minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.0.143
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

mod_id=fishermens_trap
mod_name=Fishermens Trap
mod_license=MIT License
mod_version=3.0.2
mod_group_id=com.uraneptus.fishermens_trap
mod_authors=Uraneptus
mod_description=A mod that adds a fish trap to passively collect fish by using vanilla items as baits.

jei_version=19.5.0.32